databases:
  - name: scriplay-db
    databaseName: scriplayproduction
    user: rails
    region: singapore

services:
  - type: web
    name: rails
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: scriplay-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false